/** Códigos de erro de sessão que exigem limpar cookies e reautenticar. */
export const SESSION_FATAL_CODES = new Set([
  "SESSION_REVOKED",
  "INVALID_SESSION",
  "SESSION_EXPIRED",
  "SESSION_MISMATCH",
  "INVALID_REFRESH_TOKEN",
  "REFRESH_REUSE",
  "MEMBER_CONTEXT_INVALID",
  "ENTERPRISE_CONTEXT_INVALID",
  "ENTERPRISE_NOT_SELECTED",
  "AUTH_CONTEXT_MISSING",
])
